CREATE OR REPLACE TRIGGER TRG_TB_CLIENTE
BEFORE INSERT OR UPDATE ON TB_CLIENTE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.ID_CLIENTE   := SEQ_ID_CLIENTE.NEXTVAL;
    :NEW.DT_CRIACAO   := SYSTIMESTAMP;
    :NEW.USER_CRIACAO := USER;
  END IF;

  IF UPDATING THEN
    :NEW.DT_ATUALIZACAO   := SYSTIMESTAMP;
    :NEW.USER_ATUALIZACAO := USER;
  END IF;
END;
/
